syntax="proto3";

option csharp_namespace = "DimPos.Catalog.Application.Common.Protos";


service CatalogGrpcService {
  rpc GetProductVariantsByBrand (GetProductVariantsByBrandRequest) returns (GetProductVariantsByBrandResponse);
  rpc CheckProductVariantInBrand (CheckProductVariantInBrandRequest) returns (CheckProductVariantInBrandResponse);
  rpc GetMenuProductByStore (GetMenuProductByStoreRequest) returns (GetMenuProductByStoreResponse);
  rpc GetCategoryForMenuStore (GetCategoryForMenuStoreRequest) returns (GetCategoryForMenuStoreResponse);
  rpc GetModiferGroupForMenuStore (GetModiferGroupForMenuStoreRequest) returns (GetModiferGroupForMenuStoreResponse);
  rpc GetProductVariantListByIds (GetProductVariantListByIdsRequest) returns (GetProductVariantListByIdsResponse);
  rpc GetProductVariantListByIdsForStoreMenu (GetProductVariantListByIdsForStoreMenuRequest) returns (GetProductVariantListByIdsForStoreMenuResponse);
  rpc GetProductForOrder (GetProductForOrderRequest) returns (GetProductForOrderResponse);
  rpc GetProductVariantForInternalOrder (GetProductVariantForInternalOrderRequest) returns (GetProductVariantForInternalOrderResponse);
  rpc GetIngredientsByIngredientIds (GetIngredientsByIngredientIdsRequest) returns (GetIngredientsByIngredientIdsResponse);
  rpc GetRecipeItemsByOrderItems (GetRecipeItemsByOrderItemsRequest)returns (GetRecipeItemsByOrderItemsResponse);
}
message GetCategoryForMenuStoreRequest {
  string storeId = 1;
  string brandId = 2;
}
message GetCategoryForMenuStoreResponse {
  ListCategoryResponse listCategoryResponse = 1;
}
message GetModiferGroupForMenuStoreRequest {
  string storeId = 1;
  string brandId = 2;
  ListProductVariantIds listProductVariantIds = 3;
}
message GetModiferGroupForMenuStoreResponse {
  ListModifierGroupResponse listModifierGroupResponse = 1;
}
message GetProductVariantsByBrandRequest {
  int32 page = 1;
  int32 pageSize = 2;
  optional string sortBy = 3;
  bool isAsc = 4;
  bool isActive = 5;
  string brandId = 6;
}
message GetProductVariantsByBrandResponse {
  int32 total = 1;
  int32 totalPages = 2;
  repeated ProductVariant productVariants = 3;
}
message CheckProductVariantInBrandRequest {
  string brandId = 1;
  ListProductVariantId listProductVariantId = 2;
}
message GetProductVariantListByIdsRequest {
  string brandId = 1;
  repeated string productVariantIds = 2;
}
message GetProductVariantListByIdsResponse {
  repeated ProductVariantWithImages productVariants = 1;
}
message ListProductVariantId {
  repeated string productVariantId = 1;
}
message CheckProductVariantInBrandResponse {
  bool isValid = 1;
  repeated ProductVariant extraItemProductVariants = 2;
}
message ProductVariant {
  string id = 1;
  string code = 2;
  string name = 4;
  string description = 5;
  float price = 6;
  bool isActive = 7;
  string size = 8;
  int32 displayOrder = 9;
  string sku = 10;
}
message ProductVariantWithImages {
  string id = 1;
  string code = 2;
  string name = 4;
  string description = 5;
  float price = 6;
  bool isActive = 7;
  string size = 8;
  int32 displayOrder = 9;
  string sku = 10;
  repeated ProductImage productImages = 11;
}
message ProductImage {
  string id = 1;
  string imageUrl = 2;
  bool isMainImage = 3;
  string altText = 4;
}
message GetMenuProductByStoreRequest {
  string storeId = 1;
  string brandId = 2;
  ListProductVariantIds listProductVariantIds = 3;
}
message ListProductVariantIds {
  repeated string productVariantId = 1;
}
message GetMenuProductByStoreResponse {
  optional ListCategoryResponse listCategoryResponse = 1;
  optional ListProductResponse listProductResponse = 2;
  optional ListModifierGroupResponse listModifierGroupResponse = 3;
}
message ListCategoryResponse {
  repeated CategoryResponse categories = 1;
}
message CategoryResponse {
  string id = 1;
  string code = 2;
  string name = 3;
  optional string description = 4;
  int32 displayOrder = 5;
  optional ListChildCategoryResponse childCategories = 6;
}
message ListChildCategoryResponse {
  repeated ChildCategoryResponse childCategories = 1;
}
message ChildCategoryResponse {
  string id = 1;
  string code = 2;
  string name = 3;
  optional string description = 4;
  int32 displayOrder = 5;
}
message ListProductResponse {
  repeated ProductResponse products = 1;
}
message ProductResponse {
  string id = 1;
  string code = 2;
  string name = 3;
  string description = 4;
  string imageUrl = 5;
  float price = 6;
  string categoryId = 7;
  optional ListProductVariant productVariants = 8;
  optional ListComboItemResponse comboItems = 9;
  optional ListProductVariant extraItemProductVariants = 10;
}
message ListModifierGroupResponse {
  repeated ModifierGroupResponse modifierGroups = 1;
}
message ModifierGroupResponse {
  string id = 1;
  string name = 2;
  optional string description = 3;
  SelectedTypeModifier selectedType = 4;
  optional int32 displayOrder = 5;
  bool isActive = 6;
  string brandId = 7;
  repeated string productVariantId = 8;
  optional ListModifierOptionResponse modifierOptions = 9;
}

enum SelectedTypeModifier {
  Single = 0;
  Multiple = 1;
}
message ListModifierOptionResponse {
  repeated ModifierOptionResponse modifierOptions = 1;
}
message ModifierOptionResponse {
  string id = 1;
  string name = 2;
  optional string description = 4;
  bool isActive = 5;
  float priceDelta = 6;
  string modifierGroupId = 7;
}
message ListProductVariant {
  repeated ProductVariantResponse productVariants = 1;
}
message ProductVariantResponse {
  string id = 1;
  string code = 2;
  string name = 4;
  string description = 5;
  float price = 6;
  bool isActive = 7;
  string size = 8;
  int32 displayOrder = 9;
  string sku = 10;
}
message ListComboItemResponse {
  repeated ComboItemResponse comboItems = 1;
}
message ComboItemResponse {
  string id = 1;
  int32 quantity = 2;
  int32 displayOrder = 3;
  ProductVariantResponse productVariant = 4;
}
message GetProductForOrderRequest {
  string storeId = 1;
  string brandId = 2;
  repeated ProductForOrderRequest productForOrders = 3;
}
message ProductForOrderRequest {
  string id = 1;
  string note = 2;
  int32 quantity = 3;
  repeated ModifierOptionForOrderRequest modifierOptions = 4;
}
message ModifierOptionForOrderRequest {
  string modifierOptionId = 1;
  string relatedComboProductVariantItemId = 2;
}
message GetProductForOrderResponse {
  bool isSuccess = 1;
  string errorMessage = 2;
  repeated ProductForOrderResponse productForOrders = 3;
}
message ProductForOrderResponse {
  string id = 1;
  string productName = 2;
  string productVariantName = 3;
  int32 quantity = 4;
  float unitPrice = 5;
  string note = 6;
  repeated ModifierOptionForOrderResponse modifierOptions = 7;
  repeated RecipeItemsForOrderResponse recipeItems = 8;
}
message ModifierOptionForOrderResponse {
  string id = 1;
  string modifierGroupId = 2;
  string modifierGroupName = 3;
  string modifierOptionName = 4;
  float deltaPrice = 5;
  string relatedComboProductVariantItemId = 6;
  string relatedComboProductVariantItemName = 7;
}
message RecipeItemsForOrderResponse {
  string recipeItemId = 1;
  float quantity = 2;
  IngredientForOrderResponse ingredient = 3;
}
message IngredientForOrderResponse {
  string id = 1;
  string code = 2;
  string sku = 3;
  string name = 4;
  string measureUnit = 5;
  string description = 6;
}
message GetProductVariantForInternalOrderRequest {
  string brandId = 1;
  string storeId = 2;
  repeated string productVariantId = 3;
}
message GetProductVariantForInternalOrderResponse {
  repeated ProductVariantForInternalOrder productVariants = 1;
}
message ProductVariantForInternalOrder {
  string productVariantId = 1;
  string productVariantName = 2;
  float productVariantPrice = 3;
  repeated RecipeItemsForInternalOrder recipeItems = 4;
}
message RecipeItemsForInternalOrder {
  string id = 1;
  string ingredientId = 2;
  int32 quantity = 4;
  string note = 5;
  IngredientForInternalOrder ingredient = 6;
}
message IngredientForInternalOrder {
  string id = 1;
  string sku = 2;
  string name = 3;
  string unitOfMeasure = 4;
  string description = 5;
}
message GetProductVariantListByIdsForStoreMenuRequest {
  string brandId = 1;
  repeated string productVariantIds = 2;
}
message GetProductVariantListByIdsForStoreMenuResponse {
  repeated ProductVariantWithImages productVariants = 1;
}
message GetIngredientsByIngredientIdsRequest {
  repeated string ingredientIds = 1;
}
message GetIngredientsByIngredientIdsResponse {
  repeated IngredientForGetIngredientsResponse ingredients = 1;
}
message IngredientForGetIngredientsResponse {
  string id = 1;
  string code = 2;
  string sku = 3;
  string name = 4;
  string measureUnit = 5;
  string description = 6;
}
message GetRecipeItemsByOrderItemsRequest {
  repeated OrderItemForGetRecipeItemsByOrderItemsRequest orderItems = 1;
}
message OrderItemForGetRecipeItemsByOrderItemsRequest {
  string productVariantId = 2;
  int32 quantity = 3;
}
message GetRecipeItemsByOrderItemsResponse {
  repeated RecipeItemsForOrderResponse recipeItems = 1;
}