syntax="proto3";

option csharp_namespace = "DimPos.Payment.Application.Common.Protos";

service PaymentGrpcService {
  rpc CreateB2CPayment(CreateB2CPaymentRequest) returns (CreateB2CPaymentResponse);
  rpc GetSystemPaymentMethodById(GetSystemPaymentMethodByIdRequest) returns (GetSystemPaymentMethodByIdResponse);
  rpc CreatePaymentTransaction(CreatePaymentTransactionRequest) returns (CreatePaymentTransactionResponse);
  rpc GetSystemPaymentMethodListById(GetSystemPaymentMethodListByIdRequest) returns (GetSystemPaymentMethodListByIdResponse);
  rpc UpdatePaymentMethodForOrder (UpdatePaymentMethodForOrderRequest) returns (UpdatePaymentMethodForOrderResponse);
  rpc GetPaymentTransactionByOrderId(GetPaymentTransactionByOrderIdRequest) returns (GetPaymentTransactionByOrderIdResponse);
  rpc CheckSuccessPaymentTransaction(CheckSuccessPaymentTransactionRequest) returns (CheckSuccessPaymentTransactionResponse);
  rpc CheckForCancelOrder(CheckForCancelOrderRequest) returns (CheckForCancelOrderResponse);
  rpc GetAllSystemPaymentMethods(GetAllSystemPaymentMethodsRequest) returns (GetAllSystemPaymentMethodsResponse);
}
message CreateB2CPaymentRequest {
  string storeId = 1;
  optional string customerId = 2;
  string orderId = 3;
  PaymentMethod paymentMethod = 4;
  string amount = 5;
  string currencyCode = 6;
  optional string description = 7;
}
message GetSystemPaymentMethodListByIdRequest {
  repeated string systemPaymentMethodIds = 1;
}
message GetSystemPaymentMethodListByIdResponse {
  repeated GetSystemPaymentMethodByIdResponse systemPaymentMethods = 1;
}
enum PaymentMethod {
  CASH = 0;
  QR_VIETQR = 1;
  QR_EDC = 2;
  CARD_EDC = 3;
  QR_PAYOS = 4;
}
message CreateB2CPaymentResponse {
  bool isSuccess = 1;
  string message = 2;
  optional string paymentUrl = 3;
}
message CreatePaymentTransactionResponse {
  string qrLink = 1;
  string systemPaymentMethodName = 2;
}
message CreatePaymentTransactionRequest {
  string orderId = 1;
  optional string customerId = 2;
  string accountId = 3;
  string brandId = 4;
  string storeId = 5;
  string systemPaymentMethodId = 6;
  string storePaymentMethodConfigId = 7;
  string credentialsConfig = 8;
  float amount = 9;
}
message GetSystemPaymentMethodByIdRequest {
  string id = 1;
}
message GetSystemPaymentMethodByIdResponse {
  string id = 1;
  string code = 2;
  string name = 3;
  string description = 4;
  PaymentMethod paymentMethod = 5;
  string logoUrl = 6;
}
message UpdatePaymentMethodForOrderRequest {
  string orderId = 1;
  string storeId = 2;
  string oldSystemPaymentMethodId = 3;
  string oldCredentialsConfig = 4;
  string newSystemPaymentMethodId = 5;
  string newCredentialsConfig = 6;
  float amount = 7;
}
message UpdatePaymentMethodForOrderResponse {
  string qrLink = 1;
  string systemPaymentMethodName = 2;
}
message GetPaymentTransactionByOrderIdRequest {
  string storeId = 1;
  string orderId = 2;
}
message GetPaymentTransactionByOrderIdResponse {
  string id = 1;
  string orderId = 2;
  float amount = 3;
  string currencyCode = 4;
  string systemPaymentMethodId = 5;
  PaymentMethod paymentMethod = 6;
}
message CheckSuccessPaymentTransactionRequest {
  string storeId = 1;
  string orderId = 2;
}
message CheckSuccessPaymentTransactionResponse {
  bool  isSuccess = 1;
}
message CheckForCancelOrderRequest {
  string storeId = 1;
  string orderId = 2;
  string credentialsConfig = 3;
}
message CheckForCancelOrderResponse {
  bool isSuccess = 1;
  string message = 2;
  string paymentTransactionId = 3;
}
message GetAllSystemPaymentMethodsRequest {

}
message GetAllSystemPaymentMethodsResponse {
  repeated GetSystemPaymentMethod systemPaymentMethods = 1;
}
message GetSystemPaymentMethod {
  PaymentMethod paymentMethod = 1;
  string systemPaymentMethodId = 2;
}