syntax="proto3";

option csharp_namespace = "DimPos.Store.Application.Common.Protos";
service StoreGrpcService {
  rpc GetStoresByBrandPaging (GetStoresByBrandPagingRequest) returns (GetStoresByBrandPagingResponse);
  rpc CheckStoresInBrand (CheckStoresInBrandRequest) returns (CheckStoresInBrandResponse);
  rpc GetStoreIdByAccountId (GetStoreIdByAccountIdRequest) returns (GetStoreIdByAccountIdResponse);
  rpc GetStoresByBrandId (GetStoresByBrandIdRequest) returns (GetStoresByBrandIdResponse);
  rpc GetTaxRateByStoreId (GetTaxRateForStoreMenuRequest) returns (GetTaxRateForStoreMenuResponse);
  rpc GetTaxRateAndPaymentMethodConfig(GetTaxRateAndPaymentMethodConfigRequest) returns (GetTaxRateAndPaymentMethodConfigResponse);
  rpc GetCredentialsConfigByMerchantId(GetCredentialsConfigByMerchantIdRequest) returns (GetCredentialsConfigByMerchantIdResponse);
  rpc GetBrandIdByStoreId(GetBrandIdByStoreIdRequest) returns (GetBrandIdByStoreIdResponse);
}
message GetStoresByBrandPagingRequest {
  int32 page = 1;
  int32 size = 2;
  optional string sortBy = 3;
  bool isAsc = 4;
  string brandId = 6;
}
message GetStoresByBrandPagingResponse {
  int32 total = 1;
  int32 totalPages = 2;
  repeated StoreResponse stores = 3;
}

message StoreResponse {
  string id = 1;
  string name = 2;
  string phone = 3;
  string email = 4;
  string description = 5;
  string address = 6;
  string latitude = 7;
  string longitude = 8;
  StoreStatus status = 9;
}
enum StoreStatus {
  Active = 0;
  InactiveDueToBrand = 1;
  InactiveDueToStore = 2;
}
message CheckStoresInBrandResponse {
  bool isValid = 1;
}
message CheckStoresInBrandRequest {
  string brandId = 1;
  ListStoreId listStoreId = 2;
}
message ListStoreId {
  repeated string storeId = 1;
}
message GetStoreIdByAccountIdRequest {
  string accountId = 1;
}
message GetStoreIdByAccountIdResponse {
  string storeId = 1;
}
message GetStoresByBrandIdRequest {
  string brandId = 1;
  repeated string storeIds = 2;
}
message GetStoresByBrandIdResponse {
  repeated StoreResponse stores = 1;
}
message GetTaxRateForStoreMenuRequest {
  string storeId = 1;
  string brandId = 2;
}
message GetTaxRateForStoreMenuResponse {
  string id = 1;
  string name = 2;
  float rate = 3;
}
message GetTaxRateAndPaymentMethodConfigRequest {
  string storeId = 1;
  string brandId = 2;
  string storePaymentMethodConfigId = 3;
}
message GetTaxRateAndPaymentMethodConfigResponse {
  string taxRateId = 1;
  string taxRateName = 2;
  float rate = 3;
  string systemPaymentMethodId = 4;
  string credentialsConfigAtStore = 5;
}
message GetCredentialsConfigByMerchantIdRequest {
  int64 merchantId = 1;
}
message GetCredentialsConfigByMerchantIdResponse {
  string credentialsConfig = 1;
  string storeId = 2;
}
message GetBrandIdByStoreIdRequest {
  string storeId = 1;
}
message GetBrandIdByStoreIdResponse {
  string brandId = 1;
}