syntax="proto3";

option csharp_namespace = "DimPos.Store.Application.Common.Protos";
service StoreGrpcService {
  rpc GetStoresByBrandPaging (GetStoresByBrandPagingRequest) returns (GetStoresByBrandPagingResponse);
  rpc CheckStoresInBrand (CheckStoresInBrandRequest) returns (CheckStoresInBrandResponse);
  rpc GetStoreIdByAccountId (GetStoreIdByAccountIdRequest) returns (GetStoreIdByAccountIdResponse);
  rpc GetAccountIdsByStoreIds (GetAccountIdsByStoreIdsRequest) returns (GetAccountIdsByStoreIdsResponse);
  rpc GetStoresByBrandId (GetStoresByBrandIdRequest) returns (GetStoresByBrandIdResponse);
  rpc GetTaxRateByStoreId (GetTaxRateForStoreMenuRequest) returns (GetTaxRateForStoreMenuResponse);
  rpc GetTaxRateAndPaymentMethodConfig(GetTaxRateAndPaymentMethodConfigRequest) returns (GetTaxRateAndPaymentMethodConfigResponse);
  rpc GetCredentialsConfigByMerchantId(GetCredentialsConfigByMerchantIdRequest) returns (GetCredentialsConfigByMerchantIdResponse);
  rpc GetBrandIdByStoreId(GetBrandIdByStoreIdRequest) returns (GetBrandIdByStoreIdResponse);
  rpc GetListStoreByStoreIds(GetListStoreByStoreIdsRequest) returns (GetListStoreByStoreIdsResponse);
  rpc GetPaymentMethodConfigForUpdatePaymentMethod(GetPaymentMethodConfigForUpdatePaymentMethodRequest) returns (GetPaymentMethodConfigForUpdatePaymentMethodResponse);
  rpc GetCredentialsConfigBySystemPaymentMethodId(GetCredentialsConfigBySystemPaymentMethodIdRequest) returns (GetCredentialsConfigBySystemPaymentMethodIdResponse);
  rpc GetCredentialsConfigForPayOs(GetCredentialsConfigForPayOsRequest) returns (GetCredentialsConfigForPayOsResponse);
  rpc GetStoreDetailById(GetStoreDetailByIdRequest) returns (GetStoreDetailByIdResponse);
}
message GetStoresByBrandPagingRequest {
  int32 page = 1;
  int32 size = 2;
  optional string sortBy = 3;
  bool isAsc = 4;
  optional string name = 5;
  optional string code = 6;
  string brandId = 7;
}
message GetStoresByBrandPagingResponse {
  int32 total = 1;
  int32 totalPages = 2;
  repeated StoreResponse stores = 3;
}

message StoreResponse {
  string id = 1;
  string code = 2;
  string name = 3;
  string phone = 4;
  string email = 5;
  string description = 6;
  string address = 7;
  string latitude = 8;
  string longitude = 9;
  StoreStatus status = 10;
}
enum StoreStatus {
  Active = 0;
  InactiveDueToBrand = 1;
  InactiveDueToStore = 2;
}
message CheckStoresInBrandResponse {
  bool isValid = 1;
}
message CheckStoresInBrandRequest {
  string brandId = 1;
  ListStoreId listStoreId = 2;
}
message ListStoreId {
  repeated string storeId = 1;
}
message GetStoreIdByAccountIdRequest {
  string accountId = 1;
}
message GetStoreIdByAccountIdResponse {
  string storeId = 1;
}
message GetStoresByBrandIdRequest {
  string brandId = 1;
  repeated string storeIds = 2;
}
message GetStoresByBrandIdResponse {
  repeated StoreResponse stores = 1;
}
message GetTaxRateForStoreMenuRequest {
  string storeId = 1;
  string brandId = 2;
}
message GetTaxRateForStoreMenuResponse {
  string id = 1;
  string name = 2;
  float rate = 3;
}
message GetTaxRateAndPaymentMethodConfigRequest {
  string storeId = 1;
  string brandId = 2;
  string storePaymentMethodConfigId = 3;
}
message GetTaxRateAndPaymentMethodConfigResponse {
  bool isSuccess = 1;
  string taxRateId = 2;
  string taxRateName = 3;
  float rate = 4;
  string systemPaymentMethodId = 5;
  string credentialsConfigAtStore = 6;
  string financialShiftId = 7;
  string errorMessage = 8;
}
message GetCredentialsConfigByMerchantIdRequest {
  int64 merchantId = 1;
}
message GetCredentialsConfigByMerchantIdResponse {
  string credentialsConfig = 1;
  string storeId = 2;
}
message GetBrandIdByStoreIdRequest {
  string storeId = 1;
}
message GetBrandIdByStoreIdResponse {
  string brandId = 1;
}
message GetListStoreByStoreIdsRequest {
  repeated string storeIds = 1;
}
message GetListStoreByStoreIdsResponse {
  repeated StoreResponse stores = 1;
}
message GetPaymentMethodConfigForUpdatePaymentMethodRequest {
  string storeId = 1;
  string brandId = 2;
  string oldStorePaymentMethodConfigId = 3;
  string newStorePaymentMethodConfigId = 4;
}
message GetPaymentMethodConfigForUpdatePaymentMethodResponse {
  string oldSystemPaymentMethodId = 1;
  string oldCredentialsConfigAtStore = 2;
  string newSystemPaymentMethodId = 3;
  string newCredentialsConfigAtStore = 4;
}
message GetCredentialsConfigBySystemPaymentMethodIdRequest {
  string storeId = 1;
  string brandId = 2;
  string systemPaymentMethodId = 3;
}
message GetCredentialsConfigBySystemPaymentMethodIdResponse  {
  bool isSuccess = 1;
  string errorMessage = 2;
  string systemPaymentMethodId = 3;
  string credentialsConfigAtStore = 4;
}
message GetCredentialsConfigForPayOsRequest {
  string systemPaymentMethodId = 1;
  string storeId = 2;
}
message GetCredentialsConfigForPayOsResponse {
  bool isSuccess = 1;
  string errorMessage = 2;
  string systemPaymentMethodId = 3;
  string credentialsConfigAtStore = 4;
}
message GetAccountIdsByStoreIdsRequest {
  repeated string storeIds = 1;
}
message GetAccountIdsByStoreIdsResponse {
  repeated GetAccountIdsByStoreIds responses = 1;
}
message  GetAccountIdsByStoreIds {
  string storeId = 1;
  string accountId = 2;
}
message GetStoreDetailByIdRequest {
  string storeId = 1;
}
message GetStoreDetailByIdResponse {
  string id = 1;
  string name = 2;
  string code = 3;
  string phone = 4;
  string email = 5;
  string description = 6;
  string shortName = 7;
  string address = 8;
  string latitude = 9;
  string longitude = 10;
  string managerName = 11;
  string brandId = 12;
}