<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
        <PackageReference Include="Grpc.Net.Client" Version="2.71.0" />
        <PackageReference Include="Mediator.Abstractions" Version="2.1.7" />
        <PackageReference Include="Mediator.SourceGenerator" Version="2.1.7">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DimPos.MenuCombo.Infrastructure\DimPos.MenuCombo.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Protobuf Include=".\Common\Protos\catalog.proto" GrpcServices="Client">
            <Link>Common\Protos\catalog.proto</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Protobuf>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Features\BrandMenuItems\Query\" />
    </ItemGroup>
    

</Project>
