// <auto-generated />
using System;
using DimPos.Promotion.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DimPos.Promotion.Infrastructure.Migrations
{
    [DbContext(typeof(PromotionContext))]
    [Migration("20250625101607_Add_Short_Description_For_PromotionRules")]
    partial class Add_Short_Description_For_PromotionRules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DimPos.Promotion.Domain.Entities.CampaignRuleLinks", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PromotionRuleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PromotionRuleId");

                    b.HasIndex("CampaignId", "PromotionRuleId")
                        .IsUnique();

                    b.ToTable("CampaignRuleLinks");
                });

            modelBuilder.Entity("DimPos.Promotion.Domain.Entities.CampaignStores", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActiveAtStore")
                        .HasColumnType("bit");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "StoreId")
                        .IsUnique();

                    b.ToTable("CampaignStores");
                });

            modelBuilder.Entity("DimPos.Promotion.Domain.Entities.Campaigns", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MaxTotalUsageLimit")
                        .HasColumnType("int");

                    b.Property<int?>("MaxUsagePerCustomerLimit")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("DimPos.Promotion.Domain.Entities.PromotionRules", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("PromotionRules");
                });

            modelBuilder.Entity("DimPos.Promotion.Domain.Entities.RuleActions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MaxDiscountAmountForPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PromotionRuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TargetCriteriaForItemAction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PromotionRuleId")
                        .IsUnique();

                    b.ToTable("RuleActions");
                });

            modelBuilder.Entity("DimPos.Promotion.Domain.Entities.RuleConditions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConditionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PromotionRuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PromotionRuleId");

                    b.ToTable("RuleConditions");
                });

            modelBuilder.Entity("DimPos.Promotion.Domain.Entities.CampaignRuleLinks", b =>
                {
                    b.HasOne("DimPos.Promotion.Domain.Entities.Campaigns", "Campaign")
                        .WithMany("CampaignRuleLinks")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DimPos.Promotion.Domain.Entities.PromotionRules", "PromotionRule")
                        .WithMany("CampaignRuleLinks")
                        .HasForeignKey("PromotionRuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("PromotionRule");
                });

            modelBuilder.Entity("DimPos.Promotion.Domain.Entities.CampaignStores", b =>
                {
                    b.HasOne("DimPos.Promotion.Domain.Entities.Campaigns", "Campaign")
                        .WithMany("CampaignStores")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("DimPos.Promotion.Domain.Entities.RuleActions", b =>
                {
                    b.HasOne("DimPos.Promotion.Domain.Entities.PromotionRules", "PromotionRule")
                        .WithOne("RuleActions")
                        .HasForeignKey("DimPos.Promotion.Domain.Entities.RuleActions", "PromotionRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PromotionRule");
                });

            modelBuilder.Entity("DimPos.Promotion.Domain.Entities.RuleConditions", b =>
                {
                    b.HasOne("DimPos.Promotion.Domain.Entities.PromotionRules", "PromotionRule")
                        .WithMany("RuleConditions")
                        .HasForeignKey("PromotionRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PromotionRule");
                });

            modelBuilder.Entity("DimPos.Promotion.Domain.Entities.Campaigns", b =>
                {
                    b.Navigation("CampaignRuleLinks");

                    b.Navigation("CampaignStores");
                });

            modelBuilder.Entity("DimPos.Promotion.Domain.Entities.PromotionRules", b =>
                {
                    b.Navigation("CampaignRuleLinks");

                    b.Navigation("RuleActions")
                        .IsRequired();

                    b.Navigation("RuleConditions");
                });
#pragma warning restore 612, 618
        }
    }
}
