syntax="proto3";

option csharp_namespace = "DimPos.Catalog.Application.Common.Protos";


service CatalogGrpcService {
  rpc GetProductVariantsByBrand (GetProductVariantsByBrandRequest) returns (GetProductVariantsByBrandResponse);
  rpc CheckProductVariantInBrand (CheckProductVariantInBrandRequest) returns (CheckProductVariantInBrandResponse);
  rpc GetMenuProductByStore (GetMenuProductByStoreRequest) returns (GetMenuProductByStoreResponse);
}
message GetProductVariantsByBrandRequest {
  int32 page = 1;
  int32 pageSize = 2;
  optional string sortBy = 3;
  bool isAsc = 4;
  optional ProductVariantStatus status = 5;
  string brandId = 6;
}
message GetProductVariantsByBrandResponse {
  int32 total = 1;
  int32 totalPages = 2;
  repeated ProductVariant productVariants = 3;
}
message CheckProductVariantInBrandRequest {
  string brandId = 1;
  ListProductVariantId listProductVariantId = 2;
}
message ListProductVariantId {
  repeated string productVariantId = 1;
}
message CheckProductVariantInBrandResponse {
  bool isValid = 1;
}
message ProductVariant {
  string id = 1;
  string code = 2;
  string alternativeCode = 3;
  string name = 4;
  float discountPercent = 5;
  float discountPrice = 6;
  float price = 7;
  float priceCOGS = 8;
  bool isActive = 9;
  string size = 10;
  bool isMenuDisplay = 11;
  int32 displayOrder = 12;
  ProductVariantStatus status = 13;
}
enum ProductVariantStatus {
  Active = 0;
  Inactive = 1;
  Discontinued = 2;
  Archived = 3;
}
message GetMenuProductByStoreRequest {
  string storeId = 1;
  string brandId = 2;
  ListProductVariantIds listProductVariantIds = 3;
}
message ListProductVariantIds {
  repeated string productVariantId = 1;
}
message GetMenuProductByStoreResponse {
  optional ListCategoryResponse listCategoryResponse = 1;
  optional ListProductResponse listProductResponse = 2;
}
message ListCategoryResponse {
  repeated CategoryResponse categories = 1;
}
message CategoryResponse {
  string id = 1;
  string code = 2;
  string name = 3;
  optional string description = 4;
  int32 displayOrder = 5;
  optional ListChildCategoryResponse childCategories = 6;
}
message ListChildCategoryResponse {
  repeated ChildCategoryResponse childCategories = 1;
}
message ChildCategoryResponse {
  string id = 1;
  string code = 2;
  string name = 3;
  optional string description = 4;
  int32 displayOrder = 5;
}
message ListProductResponse {
  repeated ProductResponse products = 1;
}
message ProductResponse {
  string id = 1;
  string code = 2;
  optional string alternativeCode = 3;
  string name = 4;
  string description = 5;
  string imageUrl = 6;
  float price = 7;
  string CategoryId = 8;
  optional ListProductVariant productVariants = 9;
}
message ListProductVariant {
  repeated ProductVariantResponse productVariants = 1;
}
message ProductVariantResponse {
  string id = 1;
  string code = 2;
  optional string alternativeCode = 3;
  string name = 4;
  float discountPercent = 5;
  float discountPrice = 6;
  float price = 7;
  float priceCOGS = 8;
  bool isActive = 9;
  string size = 10;
  bool isMenuDisplay = 11;
  int32 displayOrder = 12;
}