// <auto-generated />
using System;
using DimPos.MenuCombo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DimPos.MenuCombo.Infrastructure.Migrations
{
    [DbContext(typeof(MenuComboContext))]
    [Migration("20250719060323_Add_Relationship_Of_BrandMenu_And_StoreMenu")]
    partial class Add_Relationship_Of_BrandMenu_And_StoreMenu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DimPos.MenuCombo.Domain.Entities.BrandMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActiveByBrand")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("DimPos.MenuCombo.Domain.Entities.BrandMenuItems", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("DimPos.MenuCombo.Domain.Entities.StoreMenuAssignments", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrandMenuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActiveAtStore")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BrandMenuId");

                    b.ToTable("StoreMenuAssignments");
                });

            modelBuilder.Entity("DimPos.MenuCombo.Domain.Entities.StoreMenuItemAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrandMenuItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActiveAtStore")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StoreMenuAssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BrandMenuItemId");

                    b.HasIndex("StoreMenuAssignmentId");

                    b.ToTable("StoreMenuItemAvailability");
                });

            modelBuilder.Entity("DimPos.MenuCombo.Domain.Entities.BrandMenuItems", b =>
                {
                    b.HasOne("DimPos.MenuCombo.Domain.Entities.BrandMenu", "Menu")
                        .WithMany("MenuItems")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("DimPos.MenuCombo.Domain.Entities.StoreMenuAssignments", b =>
                {
                    b.HasOne("DimPos.MenuCombo.Domain.Entities.BrandMenu", "BrandMenu")
                        .WithMany("StoreMenuAssignments")
                        .HasForeignKey("BrandMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BrandMenu");
                });

            modelBuilder.Entity("DimPos.MenuCombo.Domain.Entities.StoreMenuItemAvailability", b =>
                {
                    b.HasOne("DimPos.MenuCombo.Domain.Entities.BrandMenuItems", "BrandMenuItem")
                        .WithMany("StoreMenuItemAvailability")
                        .HasForeignKey("BrandMenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DimPos.MenuCombo.Domain.Entities.StoreMenuAssignments", "StoreMenuAssignment")
                        .WithMany("StoreMenuItemAvailability")
                        .HasForeignKey("StoreMenuAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BrandMenuItem");

                    b.Navigation("StoreMenuAssignment");
                });

            modelBuilder.Entity("DimPos.MenuCombo.Domain.Entities.BrandMenu", b =>
                {
                    b.Navigation("MenuItems");

                    b.Navigation("StoreMenuAssignments");
                });

            modelBuilder.Entity("DimPos.MenuCombo.Domain.Entities.BrandMenuItems", b =>
                {
                    b.Navigation("StoreMenuItemAvailability");
                });

            modelBuilder.Entity("DimPos.MenuCombo.Domain.Entities.StoreMenuAssignments", b =>
                {
                    b.Navigation("StoreMenuItemAvailability");
                });
#pragma warning restore 612, 618
        }
    }
}
