syntax="proto3";

option csharp_namespace = "DimPos.Order.Application.Common.Protos";


service OrderGrpcService {
  rpc GetIsNeedToUpdateInventoryByOrderId (GetIsNeedToUpdateInventoryByOrderIdRequest) returns (GetIsNeedToUpdateInventoryByOrderIdResponse);
}
message GetIsNeedToUpdateInventoryByOrderIdRequest {
  string storeId = 1;
  string orderId = 2;
}
message GetIsNeedToUpdateInventoryByOrderIdResponse {
  string orderId = 1;
  bool isNeedToUpdateInventory = 2;
  repeated OrderItemResponse orderItems = 3;
}
message OrderItemResponse {
  string id = 1;
  string productVariantId = 2;
  int32 quantity = 3;
}