// <auto-generated />
using System;
using DimPos.Order.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DimPos.Order.Infrastructure.Migrations
{
    [DbContext(typeof(OrderContext))]
    [Migration("20250805192908_Change_Type_Of_TableNumberDineIn_Of_Orders_Table")]
    partial class Change_Type_Of_TableNumberDineIn_Of_Orders_Table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DimPos.Order.Domain.Entities.AppliedOrderPromotions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DiscountAmountApplied")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OrderItemsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PromotionDescriptionSnapshot")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PromotionNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("PromotionRuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PromotionTypeSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("OrderItemsId");

                    b.ToTable("AppliedOrderPromotions");
                });

            modelBuilder.Entity("DimPos.Order.Domain.Entities.AppliedTaxes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TaxNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TaxRateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TaxRateSnapshot")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("AppliedTaxes");
                });

            modelBuilder.Entity("DimPos.Order.Domain.Entities.OrderItems", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductVariantNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPriceBeforeItemDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPriceSnapshot")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("DimPos.Order.Domain.Entities.Orders", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CancelledByAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CashRoundingAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerNameSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhoneSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("FinancialShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsNeedToUpdateInventory")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PickupTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SubTotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SystemPaymentMethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SystemPaymentMethodNameSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TableNumberDineIn")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DimPos.Order.Domain.Entities.StorePurchaseOrderItems", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ApprovedQuantityByBrand")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductVariantIdSnapshot")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductVariantNameSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductVariantPriceSnapshot")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RequestedQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("StorePurchaseOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalPriceOfOrderItems")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("StorePurchaseOrderId");

                    b.ToTable("StorePurchaseOrderItems");
                });

            modelBuilder.Entity("DimPos.Order.Domain.Entities.StorePurchaseOrders", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CancellationReasonByBrand")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CancellationRequestReasonByStore")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConfirmedByBrandAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EstimatedTotalValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoteFromBrand")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NoteFromStore")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("StorePurchaseOrders");
                });

            modelBuilder.Entity("DimPos.Order.Domain.Entities.AppliedOrderPromotions", b =>
                {
                    b.HasOne("DimPos.Order.Domain.Entities.Orders", "Order")
                        .WithMany("AppliedOrderPromotions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DimPos.Order.Domain.Entities.OrderItems", null)
                        .WithMany("AppliedOrderPromotions")
                        .HasForeignKey("OrderItemsId");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DimPos.Order.Domain.Entities.AppliedTaxes", b =>
                {
                    b.HasOne("DimPos.Order.Domain.Entities.Orders", "Order")
                        .WithOne("AppliedTax")
                        .HasForeignKey("DimPos.Order.Domain.Entities.AppliedTaxes", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DimPos.Order.Domain.Entities.OrderItems", b =>
                {
                    b.HasOne("DimPos.Order.Domain.Entities.Orders", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DimPos.Order.Domain.Entities.StorePurchaseOrderItems", b =>
                {
                    b.HasOne("DimPos.Order.Domain.Entities.StorePurchaseOrders", "StorePurchaseOrder")
                        .WithMany("StorePurchaseOrderItems")
                        .HasForeignKey("StorePurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StorePurchaseOrder");
                });

            modelBuilder.Entity("DimPos.Order.Domain.Entities.OrderItems", b =>
                {
                    b.Navigation("AppliedOrderPromotions");
                });

            modelBuilder.Entity("DimPos.Order.Domain.Entities.Orders", b =>
                {
                    b.Navigation("AppliedOrderPromotions");

                    b.Navigation("AppliedTax");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("DimPos.Order.Domain.Entities.StorePurchaseOrders", b =>
                {
                    b.Navigation("StorePurchaseOrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
