syntax="proto3";

option csharp_namespace = "DimPos.Order.Application.Common.Protos";


service OrderGrpcService {
  rpc GetIsNeedToUpdateInventoryByOrderId (GetIsNeedToUpdateInventoryByOrderIdRequest) returns (GetIsNeedToUpdateInventoryByOrderIdResponse);
  rpc GetDetailForCloseFinancialShift(GetDetailForCloseFinancialShiftRequest) returns (GetDetailForCloseFinancialShiftResponse);
}
message GetIsNeedToUpdateInventoryByOrderIdRequest {
  string storeId = 1;
  string orderId = 2;
}
message GetIsNeedToUpdateInventoryByOrderIdResponse {
  string orderId = 1;
  bool isNeedToUpdateInventory = 2;
  repeated OrderItemResponse orderItems = 3;
}
message OrderItemResponse {
  string id = 1;
  string productVariantId = 2;
  int32 quantity = 3;
}
message GetDetailForCloseFinancialShiftRequest {
  string storeId = 1;
  string financialShiftId = 2;
}
message GetDetailForCloseFinancialShiftResponse {
  string financialShiftId  = 1;
  float totalGrossSalesInShift = 2;
  float totalNetSalesInShift = 3;
  float totalTaxInShift = 4;
  float totalDiscountInShift = 5;
  float totalCashRoundingInShift = 6;
}