<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\DimPos.Order.Infrastructure\DimPos.Order.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
      <PackageReference Include="Mediator.Abstractions" Version="2.1.7" />
      <PackageReference Include="Mediator.SourceGenerator" Version="2.1.7">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <None Remove="Common\Protos\order.proto" />
        <Protobuf Include="Common\Protos\order.proto" GrpcServices="Server">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
            <Access>Public</Access>
            <ProtoCompile>True</ProtoCompile>
            <ProtoRoot></ProtoRoot>
            <CompileOutputs>True</CompileOutputs>
            <OutputDir>obj\Debug/net9.0/</OutputDir>
            <Generator>MSBuild:Compile</Generator>
        </Protobuf>
    </ItemGroup>
    
    <ItemGroup>
        <Protobuf Include=".\Common\Protos\catalog.proto" GrpcServices="Client">
            <Link>Common\Protos\catalog.proto</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Protobuf>
    </ItemGroup>
    <ItemGroup>
        <Protobuf Include=".\Common\Protos\store.proto" GrpcServices="Client">
            <Link>Common\Protos\store.proto</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Protobuf>
    </ItemGroup>
    <ItemGroup>
        <Protobuf Include=".\Common\Protos\promotion.proto" GrpcServices="Client">
            <Link>Common\Protos\promotion.proto</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Protobuf>
    </ItemGroup>
    <ItemGroup>
        <Protobuf Include=".\Common\Protos\payment.proto" GrpcServices="Client">
            <Link>Common\Protos\payment.proto</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Protobuf>
    </ItemGroup>
    <ItemGroup>
        <Protobuf Include=".\Common\Protos\inventory.proto" GrpcServices="Client">
            <Link>Common\Protos\inventory.proto</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Protobuf>
    </ItemGroup>
    
</Project>
